### ISSUE TITLE
Create script is out Outputing wrong string value on window type "Full Screen"

### ISSUE THREAD

**Issue by rderewianko** [JAMFSupport/JAMF-Helper-GUI#1]
EG: 
Wrong: 
"/Library/Application Support/JAMF/bin/jamfHelper.app/Contents/MacOS/jamfHelper" -windowType **fullscreen** -heading "test" -description "test"

Where windowType is fullscreen
Correct:
"/Library/Application Support/JAMF/bin/jamfHelper.app/Contents/MacOS/jamfHelper" -windowType **fs** -heading "test" -description "test"
As per documentation window type should just be fs for full screen

**Comment by jordanpatrick** [comment]
This issue has been corrected in v1.0 build 7. The project has been updated and a release has been compiled and uploaded to Github.
