### ISSUE TITLE
can't open in xcode 7.3

### ISSUE THREAD

**Issue by marklamont** [JAMFSupport/JAMF-Helper-GUI#2]
you can't open the project in xcode 7.3
![screenshot 2016-05-10 07 35 10](https://cloud.githubusercontent.com/assets/8194501/15137424/c8273f10-1681-11e6-8230-d9e748faeacb.jpg)

**Comment by jordanpatrick** [comment]
It looks like this was mainly a problem with the syntax in the for loops, and also needed to add 2 "self" references to function calls.
