### ISSUE TITLE
"Fatal Error: Index out of range" ViewController.swift:415

### ISSUE THREAD

**Issue by prbsparx** [JAMFSupport/JAMF-Helper-GUI#3]
When attempting to create a locked HUD, with the below settings, JAMF Helper GUI crashes with a fatal error: Index out of range on ViewController.swift:415

Type: HUD
Position: Center
Lock: Yes
Title: Test
Heading: test
Description: "Your computer will reboot in:"
Button 1: OK
Default: 1
Timeout: 60
Countdown: Yes
Text: Seconds

**Comment by jordanpatrick** [comment]
This issue should be resolved. I've confirmed using the latest release the "center" window position is again usable.
